export const addLeadsFormUtils = (leads) => [
  {
    _id: 1,
    label: "Name",
    name: "name",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "name",
    value: leads.name,
    type: "text",
  },
  {
    _id: 2,
    label: "Contact",
    name: "contact",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "contact",
    type: "tel",
    value: leads.contact,
    maxLength: "10",
  },
  {
    _id: 3,
    label: "Email",
    name: "email",
    div_class: "col-12 col-md-6 col-xxl-4",
    type: "email",
    id: "email",
    value: leads.email,
  },
  {
    _id: 4,
    label: "Profile",
    name: "Profile",
    div_class: "col-12 col-md-6 col-xxl-4",
    type: "text",
    id: "Profile",
    value: leads.Profile,
  },
  // {
  //   id: 5,
  //   label: "User Name",
  //   name: "userName",
  //   div_class: "col-12 col-md-6 col-xxl-4",
  //   id: "userName",
  //   value: leads.userName,
  //   type: "text",
  // },
  {
    _id: 6,
    label: "Sub Profile",
    name: "subprofile",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "subprofile",
    value: leads.subprofile,
    type: "text",
  },
  // {
  //   id: 7,
  //   label: "Company",
  //   name: "company",
  //   div_class: "col-12 col-md-6 col-xxl-4",
  //   id: "company",
  //   value: leads.company,
  //   type: "text",
  // },
  // {
  //   id: 8,
  //   label: "Job Title",
  //   name: "jobTitle",
  //   div_class: "col-12 col-md-6 col-xxl-4",
  //   id: "jobTitle",
  //   value: leads.jobTitle,
  //   type: "text",
  // },
  {
    _id: 9,
    label: "Preferred Locations",
    name: "preferredLocations",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "preferredLocations",
    value: leads.preferredLocations,
    type: "text",
  },
  {
    _id: 10,
    label: "Total Experience",
    name: "totalExp",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "totalExp",
    value: leads.totalExp,
    type: "text",
  },
  {
    _id: 11,
    label: "Current Company Name",
    name: "currentCompanyName",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "currentCompanyName",
    value: leads.currentCompanyName,
    type: "text",
  },
  {
    _id: 12,
    label: "Current Company Degination",
    name: "currentCompaniDesignation",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "currentCompaniDesignation",
    value: leads.currentCompaniDesignation,
    type: "text",
  },
  {
    _id: 13,
    label: "Department",
    name: "department",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "department",
    value: leads.department,
    type: "text",
  },
  // {
  //   id: 14,
  //   label: "Role",
  //   name: "role",
  //   div_class: "col-12 col-md-6 col-xxl-4",
  //   id: "role",
  //   value: leads.role,
  //   type: "text",
  // },
  // {
  //   id: 15,
  //   label: "Industry",
  //   name: "industry",
  //   div_class: "col-12 col-md-6 col-xxl-4",
  //   id: "industry",
  //   value: leads.industry,
  //   type: "text",
  // },
  {
    _id: 16,
    label: "Expected Salary",
    name: "anualSalary",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "anualSalary",
    value: leads.anualSalary,
    type: "text",
  },
  {
    _id: 17,
    label: "Under Graduate Degree",
    name: "underGraduateDegree",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "underGraduateDegree",
    value: leads.underGraduateDegree,
    type: "text",
  },
  {
    _id: 18,
    label: "up specialization",
    name: "upSpecelization",
    div_class: "col-12 col-md-6 col-xxl-4",
    id: "upSpecelization",
    value: leads.upSpecelization,
    type: "text",
  },
];
