export const COUNTRY = "COUNTRY";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const INCREASESTEPS = "INCREASESTEPS";
export const GETCANDIDATEINFO = "GETCANDIDATEINFO";
export const INTERVIEWNOTIFICATION = "INTERVIEWNOTIFICATION";
export const JOININGNOTIFICATION = "JOININGNOTIFICATION";
